name: General Issue
description: 버그 리포트 또는 기능 제안을 위한 템플릿
title: "[버그] ..." 또는 "[기능제안] ..."
labels: ["needs triage"]
assignees: []

body:
  - type: dropdown
    id: issue-type
    attributes:
      label: 이슈 유형
      description: 이 이슈는 어떤 유형인가요?
      options:
        - 버그 리포트
        - 기능 제안
        - 문서 개선
        - 기타
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 어떤 문제가 있거나 어떤 기능을 제안하고 싶은지 간단히 설명해주세요.
      placeholder: 예) 로그인 버튼을 클릭해도 아무 반응이 없습니다.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법 (버그일 경우)
      description: 문제를 어떻게 재현할 수 있는지 단계별로 설명해주세요.
      placeholder: |
        1. 로그인 페이지로 이동
        2. 아이디/비밀번호 입력
        3. 로그인 버튼 클릭
        4. 반응 없음
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: 실행 환경
      description: 해당 이슈를 발견한 환경 정보를 입력해주세요.
      placeholder: 예) Chrome 123 / macOS 14.1 / Node.js 20.10
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷/로그
      description: 문제를 설명하는 데 도움이 될 수 있는 이미지나 콘솔 로그 등을 첨부해주세요.
      placeholder: drag & drop your image here, or paste error logs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 기타 참고 사항
      description: 이외에 공유하고 싶은 내용이 있다면 작성해주세요.
    validations:
      required: false
